Readme writeup
OpenNullanoid/rektifiedfire-docs-core pull request #1
Opened 2023-05-10 12:17 UTC by Kabir404

This would clear things out for everyone. Initially written by myself but rewritten again by OpenAI ChatGPT

2023-05-10 12:21 UTC, mdhishamsayed commented on README.md
> ++ **Screenplay Script** - Includes the screenplay for the game
remove word script

2023-05-10 12:22 UTC, mdhishamsayed commented on README.md
> +The notorious DarkWave criminal organization has been conducting illegal activities within Kioxia, providing high-tech gadgets to criminals. However, when the organization's human personnel escaped,
add some introduction to the darkwave

2023-05-10 12:23 UTC, mdhishamsayed commented on README.md
> +As RektifierKX, players must infiltrate the abandoned DarkWave facility stealthily, collect information and avoid detection. By using exceptional skills and making strategic decisions, players uncove
law and order

2023-05-10 12:24 UTC, mdhishamsayed commented on README.md
> ++ **Development Planning** - Includes necessary files crucial to the development process
steps, like first develop backend then graphics etc

2023-05-10 12:24 UTC, mdhishamsayed commented on README.md
> +Depth Walker is an action-packed first-person shooter (FPS) game that falls under the sci-fi action-adventure genre. Directed by Kabir Akzaman and developed by OpenNullanoid community contributors, D
exciting game to play

2023-05-10 12:24 UTC, mdhishamsayed commented on README.md
> +In the game, players take on the role of RektifierKX, an advanced robot agent created by Mechmorphix, a reputable AI technology company working with law enforcement agencies in Kioxia city.
use some simpler names

2023-05-10 12:26 UTC, mdhishamsayed reviewed
Kabir is requested to look into the necessary changes

2023-05-10 12:26 UTC, mdhishamsayed requested changes
Kabir is requested to look into the necessary changes

2023-05-10 12:26 UTC, mdhishamsayed requested changes
Kabir is requested to look into the necessary changes

2023-05-10 15:03 UTC, Kabir404 commented
> Kabir is requested to look into the necessary changes

I would look into that later

2023-05-11 01:13 UTC, Kabir404 commented on README.md
> +In the game, players take on the role of RektifierKX, an advanced robot agent created by Mechmorphix, a reputable AI technology company working with law enforcement agencies in Kioxia city.
RektifierKX has its nickname which is Rex while DarkWave and Mechamorphix are still reasonable...

2023-05-11 01:14 UTC, Kabir404 commented on README.md
> ++ **Development Planning** - Includes necessary files crucial to the development process
Yes, yes, that would be in the documentation hosted in this repo...

2023-05-11 01:23 UTC, Kabir404 commented on README.md
> ++ **Screenplay Script** - Includes the screenplay for the game
I dont think thats that big of an issue...

2023-05-11 01:23 UTC, Kabir404 commented on README.md
> +The notorious DarkWave criminal organization has been conducting illegal activities within Kioxia, providing high-tech gadgets to criminals. However, when the organization's human personnel escaped,
did it

2023-05-11 11:56 UTC, mdhishamsayed approved these changes

2023-05-11 11:57 UTC, merged